[project]
name = "imagetrt"
version = "0.1.0"
description = "Fast image inference/training with TensorRT and PyTorch"
readme = "README.md"
requires-python = ">=3.9"
authors = [{name = "Sayedmorteza Malaekeh (Ali)"}]
dependencies = []

[tool.ruff]
line-length = 100
target-version = "py311"
